# Generated by Django 3.0.8 on 2020-07-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0004_auto_20200719_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
