# Generated by Django 3.0.8 on 2020-07-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0006_auto_20200730_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
