# Generated by Django 3.0.8 on 2020-07-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0008_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='url1',
        ),
    ]
