# Generated by Django 3.0.8 on 2020-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0010_remove_shippingaddress_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
