# Generated by Django 3.0.8 on 2020-08-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0011_auto_20200731_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
